Flink 1.12 dev
StarRocks/flink-connector-starrocks pull request #35
Opened 2021-12-16 10:53 UTC by waittttting

2021-12-27 06:57 UTC, hffariel requested changes

2021-12-27 06:57 UTC, hffariel commented on build-thrift.sh
> +#!/bin/bash
lack of windows batch script

2021-12-27 06:57 UTC, hffariel commented on pom.xml
> +                                    <include>com.fasterxml.jackson.core:jackson-annotations</include>
Consider to replace jackson with fastjson to reduce dependencies.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/StarRocksSource.java
> +     * @param flinkSchema       FlinkSchema
lack of @return in the comment

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/StarRocksSource.java
> +package com.starrocks.connector.flink;
lack of license announcement

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +    private static final Logger LOG = LoggerFactory.getLogger(StarRocksSinkManager.class);
Wrong class for the logger

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +        beXTablets.forEach((be, tablets) -> {
Consider to replace the foreach with parallelstream map

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +                } else {
redundant `else` block here

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +        String url = "http://" + httpNode + "/api/" + sourceOptions.getDatabaseName() + "/" + sourceOptions.getTableName() + "/_query_plan";
use stringbuilder

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +        CloseableHttpResponse response = null;
wrap with try(){} block for auto-releasing

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +            } else {
redundant else block

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +                LOG.warn("Request failed with code:{}", requsetCode);
Consider to add a gap between each retry.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +        if (null == respEntity) {
move these lines into the retrying loop

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryVisitor.java
> +    private int executeCountQuery(String query, String... args) throws ClassNotFoundException, SQLException {
use the pre-existed `executequery` method

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryVisitor.java
> +        dbConn.close();
should be replaced with jdbcConnProvider.close()

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            flinksRowsCount += root.getRowCount();
flinksRowsCount -> flinkRowsCount

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            if (flinkTypeRoot == LogicalTypeRoot.DATE) {
1. should have a continue inside every `if` block
2. consider to replace the `transToxxx` with a bunch of translators that implement a `trans` method.
3. put the translators into the typesmap.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            int timestamp = (int)date.atStartOfDay(ZoneOffset.ofHours(8)).toLocalDate().toEpochDay();
GMT+8 here only ?

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            String formatStringLong = "yyyy-MM-dd HH:mm:ss.SSSSSS";
make these formats as const

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            LocalDate date = LocalDate.parse(value, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
make the date format as const

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +                value = DataUtil.addZeroForNum(value + ".", formatStringLong.length());
stringbuilder here

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            DateTimeFormatter df = DateTimeFormatter.ofPattern(formatStringLong);
make the formatter as a const

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
> +            while (dataReader.hasNext()) {
code format

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
> +        } else {
return  and remove the else block

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
> +        String filter = String.join(" and ", filterList);
don't really get what's going on here, why always the `and` and `=` operator.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +    private static final String COUNTER_TOTAL_COUNT_DATA_ROWS_OF_SINGLE_SUBTASK = "totalCountDataRowsOfSingleSubTask";
totalscannedrows?

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        if (this.sourceOptions.getColumns().trim().equals("count(*)")) {
what if `count(1)` `count(*) as xxx` etc...

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        String columns = options.getColumns().equals("") ? "*" : options.getColumns();
equals("") -> isEmpty()

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        this.dataReaderList.forEach(dataReader -> {
use parallel foreach function

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java
> +    public ChangelogMode getChangelogMode() {
why insertOnly?

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java
> +        return Result.of(filtersExpressions, new ArrayList<>());
filters that can't be accepted here like 'like xxx' 'in (xxx, xxx)' 'between' etc... should all be returned.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            if (!Const.DataTypeRelationMap.containsKey(flinkTypeRoot)) {
validations executed too many times?

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceCommonFunc.java
> +        } else if (subTaskCount < beXTabletsListCount) {
redundant else

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceCommonFunc.java
> +            if (x > 1) {
return and remove the if block

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceCommonFunc.java
> +        return starrocksQueryVisitor;
should use a singleton queryvisitor.

2021-12-27 06:57 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/struct/PushDownHolder.java
> +public class PushDownHolder {
serializable?

2021-12-27 06:57 UTC, hffariel commented on src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceBaseTest.java
> +                        InputStream in = socket.getInputStream();
refer to the latest code on the `dev` branch

2021-12-27 06:57 UTC, hffariel commented on src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceBaseTest.java
> +        serverSocket = new ServerSocket(AVAILABLE_HTTP_PORT);
refer to the latest code on the dev branch

2021-12-27 06:57 UTC, hffariel commented on src/test/resources/rowsData
> +-1, -1, -1, -1, -16, 2, 0, 0, 16, 0, 0, 0, 0, 0, 10, 0, 12, 0, 6, 0, 5, 0, 8, 0, 10, 0, 0, 0, 0, 1, 4, 0, 12, 0, 0, 0, 8, 0, 8, 0, 0, 0, 4, 0, 8, 0, 0, 0, 4, 0, 0, 0, 13, 0, 0, 0, -112, 2, 0, 0, 80,
make it smaller

2021-12-27 06:58 UTC, hffariel commented
Also, need to gain the coverage of the UT test, and add IT tests.

2022-01-11 09:34 UTC, hffariel requested changes

2022-01-11 09:34 UTC, hffariel commented on build-thrift.sh
> +#!/bin/bash
why couldn't use the binary package here as you did in the  build-thrift.bat.

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +        if (respString == "") {
String.isEmpty() or "".equals()

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +
remove the empty line

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +            case Const.DATA_TYPE_STARROCKS_CHAR:
case a:
case b:
  break;

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceCommonFunc.java
> +        StarRocksQueryPlanVisitor starRocksQueryPlanVisitor = new StarRocksQueryPlanVisitor(sourceOptions);
make it singleton as well

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLUFunction.java
> +/*
LU -> LRU ?

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
> +        String SQL = "select * from " + sourceOptions.getDatabaseName() + "." + sourceOptions.getTableName();
make the databaseName and tableName back quoted;
use stringbuilder instead of `+`

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
> +        lists.get(0).forEach(beXTablets -> {
remove dataReaderList and tmpDataList, using parallelStream()->map()->flat()->collect(groupby) instead.

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        if (this.sourceOptions.getColumns().trim().contains("count(")) {
toLowerCase

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        String SQL = "select";
stringbuilder

2022-01-11 09:34 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
> +        if (!(filter == null || filter.isEmpty())) {
!Strings.isNullOrEmpty()

2022-01-11 09:34 UTC, hffariel commented on src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceBaseTest.java
> +/*
lack of ut test cases

2022-01-12 13:21 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryPlanVisitor.java
> +
remove the first empty line( including all the other funcitons )

2022-01-12 13:21 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
> +        for (int colIndex = 0; colIndex < this.selectColumns.length; colIndex ++) {
could make this loop parallel?

2022-01-12 13:21 UTC, hffariel commented on src/main/java/com/starrocks/connector/flink/table/source/struct/Const.java
> +    static {
better not using the static block to `put`, using singleton instead

2022-01-13 04:00 UTC, waittttting commented on build-thrift.sh
> +#!/bin/bash
Not found official bin in
https://dlcdn.apache.org/thrift/0.13.0
and
https://github.com/apache/thrift/releases

2022-01-13 12:02 UTC, hffariel approved these changes

2022-01-13 12:03 UTC, merged